directories:
  output: release
  buildResources: resources
productName: TearDownReport
appId: org.develar.TearDownReport
files:
  - filter:
      - dist/
      - electron-builder.yml
      - build/
      - node_modules/
      - app.html
      - main.prod.js
      - main.prod.js.map
      - package.json
      - app/**/*
win:
  icon: /resources/icons/aeropartsicon_1Jk_icon.ico
  target:
    - nsis
    - msi
  publish:
    - github
nsis:
  oneClick: false
  allowElevation: true
  perMachine: true
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  include: build/installer.nsh
  installerIcon: aeropartsicon_1Jk_icon.ico
  installerHeaderIcon: aeropartsicon_1Jk_icon.ico
  deleteAppDataOnUninstall: true
dmg:
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
linux:
  target:
    - deb
    - rpm
    - AppImage
  category: Development
publish:
  provider: github
  owner: staniszmatt
  repo: iir_Report
  private: false
  releaseType: release
electronVersion: 8.5.2
